### ISSUE TITLE
There is no XML Tools: View XML Tree command available

### ISSUE THREAD

**Issue by sashafp10** [DotJoshJohnson/vscode-xml#346] opened 2021-02-09 05:14 UTC
XML Tools: View XML Tree is not available

![image](https://user-images.githubusercontent.com/22002032/107318718-f79d7c80-6acf-11eb-859c-adca37034f13.png)

Tools:
v 2.5.1

VS Code:
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by taylormr** [comment] 2021-02-24 21:04
I have the same issue. I see other commands, but not view XML tree.

**Comment by DotJoshJohnson** [comment] 2021-02-24 21:24
Duplicate of #216.

This command was removed in version 1.9: https://github.com/DotJoshJohnson/vscode-xml/wiki/xml-tree-view

**Closed as completed by DotJoshJohnson** 2021-02-24 21:24 UTC
Labels: Duplicate, Module: XML Tree View

**Comment by GF-Huang** [comment] 2021-04-22 21:47
Where's the tree view? I can't see it, please give a screenshot.
