### ISSUE TITLE
Formatter is not aligning tags in Visual code

### ISSUE THREAD

**Issue by ashisjena** [DotJoshJohnson/vscode-xml#188] opened 2018-06-04 17:34 UTC
#### Description
The formatter is not aligning tags and is formatting with varied indentation. Below is an example
Ex. 
`<assign location="dnis" expr="_event.data.dnis ? _event.data.dnis : dnis"/>
<assign location="deviceId" expr="_event.data.vi ? tfs.utils.trimAni(_event.data.vi) : (_event.data.ani ? tfs.utils.trimAni(_event.data.ani) : '')"/>
<assign location="session_uuid" expr="_event.data.sessionid ? _event.data.sessionid : (_event.data.call_uuid ? _event.data.call_uuid : '') "/>
<assign location="beginTimeStamp" expr="_event.data.begintimestamp ? _event.data.begintimestamp : beginTimeStamp"/>
<assign location="endTimeStamp" expr="_event.data.endtimestamp"/>
<assign location="callerhangup" expr="_event.data.callerhangup"/>`

![image](https://user-images.githubusercontent.com/9766652/40932269-6b0454ee-684b-11e8-8e84-935aa75f467e.png)
#### Formatter Implementation
Which XML Formatter implementation are you using (the value of your "xmlTools.xmlFormatterImplementation": "v2"

#### XML Tools Version
2.2.0

#### VS Code Version
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

#### Operating System
Windows 10 Pro
Version 1607
OS Build 14393.2189

**Comment by DotJoshJohnson** [comment] 2018-06-04 18:55
Duplicate of #187. Likely broken by my change in #177.

**Closed as completed by DotJoshJohnson** 2018-06-04 18:55 UTC
Labels: Duplicate
