### ISSUE TITLE
File has to be .xml in order for formatting to work

### ISSUE THREAD

**Issue by nibras85** [DotJoshJohnson/vscode-xml#63] opened 2016-07-13 14:58 UTC
It would be nice if I could just open VS Code, paste some XML and format it without having to save it to a .xml file first

**Comment by dander** [comment] 2016-07-21 17:44
One workaround is to change the document language to XML, so that you don't have to save the file. Default keyboard shortcut for this appears to be Ctrl+K, M

**Comment by DotJoshJohnson** [comment] 2016-07-22 16:12
This is a duplicate of  #47. Unfortunately, this is a limitation of VS Code. The formatting API (which we hook into to provide XML formatting) is only activated when a given language is selected. As @dander mentioned, you can change the language to XML without saving the file to gain formatting functionality.

**Closed as completed by DotJoshJohnson** 2016-07-22 16:12 UTC
Labels: Duplicate

**Comment by nibras85** [comment] 2016-07-22 16:59
Thank you very much.
