### ISSUE TITLE
Invalid Count Value Error.

### ISSUE THREAD

**Issue by jpwijbenga** [DotJoshJohnson/vscode-xml#291] opened 2019-11-19 16:40 UTC
#### Description
Formatter gives cryptic error message: "Invalid Count Value" when trying to format small XML. Not sure if the document is faulty or formatter has a bug.
```
<?xml version="1.0" encoding="UTF-8"?>
<a>
	The Total (<value-of />) is not equal to the sum (<value-of />).
</a>
```

#### Formatter Implementation
v2

#### XML Tools Version
2.5.0

#### VS Code Version
1.40.1 User

#### Operating System
Win10 Ent (x64) 1809

**Comment by SebastianZ** [comment] 2020-05-22 09:39
This seems to be a bug in the formatter.

Here's another simple test case:
```xml
<x>foo<y><z>bar</z></y></x>
```

Trying to format this also results in an "Invalid count value" error.

Though if you insert a line break after "foo" like this

```xml
<x>foo
<y><z>bar</z></y></x>
```

the XML will be formatted correctly.

Sebastian

**Comment by DotJoshJohnson** [comment] 2020-07-07 02:45
This should be fixed by #317.

**Closed as completed by DotJoshJohnson** 2020-07-07 02:45 UTC
Labels: Bug, Module: XML Formatter

**Comment by SebastianZ** [comment] 2020-09-06 21:58
I can confirm that this issue is gone in the latest version.

The output of my example looks like this now after formatting:

```xml
<x>foo<y>
  <z>bar</z>
</y>
</x>
```

I had expected it to format it like this:

```xml
<x>foo
  <y>
    <z>bar</z>
  </y>
</x>```

Though at least the error is gone, so thank you for fixing this!

Sebastian
