### ISSUE TITLE
Preserve White Space

### ISSUE THREAD

**Issue by mikeburgh** [DotJoshJohnson/vscode-xml#77] opened 2016-11-09 15:46 UTC
Hi, 

Great extension, but wondering if it can perseve the whitepace inside nodes..

For example: 

```xml
<root><child>Line 1

Line 2

Line 3</child></root>
```
Becomes

```xml
<root>
  <child>Line 1Line 2Line 3</child>
</root>
```
Where as it would be great if it could keep the white space inside the nodes..

```xml
<root>
  <child>Line 1

Line 2

Line 3</child>
</root>
```

**Comment by DotJoshJohnson** [comment] 2016-12-20 02:53
Duplicate of #59. This will be tracked there.

**Closed as completed by DotJoshJohnson** 2016-12-20 02:53 UTC
Labels: Duplicate
