### ISSUE TITLE
xml tools not showing for large file in VS Code 64 bit Insiders

### ISSUE THREAD

**Issue by jyoungl6** [DotJoshJohnson/vscode-xml#122] opened 2017-08-09 17:34 UTC
I downloaded the VS Code 64bit Insider in the hope that it could handle some rather large XML files (the 32 bit version complained the files were too large). I was able to load a large file (256 MB) with no problem but XML Tools options are not present for this file - No formatting or syntax highlighting. Smaller XML files do show XML Tools capability.

**Comment by DotJoshJohnson** [comment] 2018-01-28 02:26
This was reported in issue #95 as well. In response to that issue, I added a "Format as XML" command that should be available for all file types. Does this command not appear as an option, either?

**Comment by DotJoshJohnson** [comment] 2018-03-02 03:27
Moving to backlog for now until we can get more information.

**Comment by Zyxious** [comment] 2018-03-12 08:10
I also have this problem opening large XML files (67MB). The new command you added does show up (Ctrl+Shift+P, "Format" -> "Xml Tools: Format as Xml", "Format Document") but when I activate it nothing happens. Same procedure on a 22kB xml file works fine. 

I also noticed that the XML syntax highlighting stops working on large xml files. My guess is that there is some kind of restriction in VS Code.

Any how I found a large xml sample file on the page belowthat will show you the problem.
http://www.xml-benchmark.org/downloads.html, click on the ready-made document below the data generator downloads and you will get a 100 MB large xml file. I use VS Code 1.12.0 and XML Tools 1.9.2.

**Comment by robgilliam** [comment] 2018-04-27 08:30
Same problem as Zyxious working with a 16.1MB XML file.

I have VS Code (x64 architecture) version 1.22.2 with XML Tools 1.9.2 installed.

(Small files work fine)

**Comment by dermoench42** [comment] 2018-05-18 09:00
Same here on Gentoo Linux
```
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Datum 2018-05-10T16:04:33.747Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64
```
Open a 512 Mb xml with some base64 encoded images I recognized:
It takes 5s (i5-6700) to open and display something as unhighlighted text.
[shift][ctrl][F] - please format - shows: 'There is is no document formatter for 'xml' Files installed.'
Choosing the command from the command palette 'XML Tools: Format as XML' doesn't seem to do anything. No cpu increases activity, no additional memory is grabbed.

Take a look on dev tools / console thers is shown:```
```
[Extension Host] XML language client and server are ready
/home/peters/bin/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] activate extension
console.ts:136 [Extension Host] Cannot execute xmlTools.formatAsXml because there is no active text editor.
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```
It seems there are a few limits, file Size? tag content size? execution time? on the editor or language server?

ervin

BTW: eclipse oxygen 3a opened the xml file after increasing the java memory limits dramaticaly (4G/8G) but also didn't format it.

**Comment by DotJoshJohnson** [comment] 2018-05-25 03:50
So far, this seems like a limitation imposed by VS Code. The Format as XML command appears simply because it is defined in the extension's manifest. But Code is not activating the extension in time to respond to the command. As far as that language client/server message in the console, that isn't coming from XML Tools as it does not implement a language server at all.

I should also note that XML syntax highlighting is provided by VS Code, not XML Tools. So if Code fails to even highlight the document, it probably hasn't bothered to activate the extension either.

I'll keep this open to continue gathering info as it may be useful to the core VS Code team if they intend to address these large file issues. Thanks for taking the time to provide some info!

**Comment by ewbi** [comment] 2018-06-07 09:01
I've encountered this issue with a simple 40 MB XML file (Windows 10, latest VS Code 1.24).  Definitely not an XML Tools issue.  Not sure why (no time to debug VS Code), but during command execution, VS Code's commands.registerTextEditorCommand call to extHostEditors.getActiveTextEditor() in extHost.api.impl.ts returns nothing resulting in console.warn('Cannot execute ' + id + ' because there is no active text editor.'); - so, never getting to XML Tools.

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts

**Comment by Zyxious** [comment] 2018-06-07 09:21
It is sad, but this seem to be by design:
https://github.com/Microsoft/vscode/issues/33460

**Comment by ewbi** [comment] 2018-06-07 09:54
Interesting.  I saw the "...tokenization, wrapping and folding have been turned off for this large file in order to reduce memory usage and avoid freezing or crashing" message and choose to "forcefully enable features", which sets "editor.largeFileOptimizations": false, so I thought that would be suffficient for overridding that large file limit, at least wrt extHostEditors.getActiveTextEditor().  Guess not.

**Comment by DotJoshJohnson** [comment] 2018-06-12 00:23
Thanks for the input, everyone. With this being squarely in VS Code's court for now (and being by design), I'm closing this issue.

**Closed as completed by DotJoshJohnson** 2018-06-12 00:23 UTC
Labels: Bug, Dependency Issue, Needs Information
