### ISSUE TITLE
Please remove annoying popup!

### ISSUE THREAD

**Issue by ALIENQuake** [DotJoshJohnson/vscode-xml#268] opened 2019-03-26 09:04 UTC
**Description**
There is no way to disable popup. I don't want to see it anymore.

**Screenshots**
`Heads up! We've rewritten the XML formatter. If you liked the old one better, it's still there. Just set the 'xmlTools.xmlFormatterImplementation' setting to 'classic'.`

**Extension Version**
2.4.0

**VS Code Version**
1.32.3

**Operating System**
Windows 10

**Comment by rsxdalv** [comment] 2019-04-19 08:09
Duplicate of #267

**Closed as completed** 2019-04-19 08:43 UTC
Labels: Duplicate
